### PR TITLE
Update to latest (0.19) version of crossterm crate

### PR DESCRIPTION
**Pull request by Eolu**
Just updated this fork. 

Tested and working on a little dummy page: [test](https://www.lamprey.zone/terminal)

### CODE REVIEW

**Comment by rrbutani** [comment]
hey, thanks for the PR @Eolu! 😄

I'm planning to (finally) get back to finishing `xterm-js-sys` and working on getting this fork upstreamed sometime in the next couple of weeks but please let me know if there's anything quick I can do to make this stuff more usable or if you run into any issues.

IIRC `xterm-js-sys` relies on a couple of patches to `wasm-bindgen` that aren't yet upstreamed so that the option structs are read correctly on the JS side; let me know if you run into this and I can try to update my `wasm-bindgen` fork so Cargo won't complain about the `[patch.crates-io]` entry.

---

I noticed that the `[patch]` entry for `xterm-js-sys` was [commented out](https://github.com/rrbutani/crossterm/pull/1/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L82-R83):

https://github.com/rrbutani/crossterm/blob/2b6bbf2efe7da42457d83dbb64079b075f5628ad/Cargo.toml#L83

Was this intentional?

**Comment by Eolu** [comment]
> 
> 
> hey, thanks for the PR @Eolu! 😄
> 
> I'm planning to (finally) get back to finishing `xterm-js-sys` and working on getting this fork upstreamed sometime in the next couple of weeks but please let me know if there's anything quick I can do to make this stuff more usable or if you run into any issues.
> 
> IIRC `xterm-js-sys` relies on a couple of patches to `wasm-bindgen` that aren't yet upstreamed so that the option structs are read correctly on the JS side; let me know if you run into this and I can try to update my `wasm-bindgen` fork so Cargo won't complain about the `[patch.crates-io]` entry.
> 
> I noticed that the `[patch]` entry for `xterm-js-sys` was [commented out](https://github.com/rrbutani/crossterm/pull/1/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L82-R83):
> 
> https://github.com/rrbutani/crossterm/blob/2b6bbf2efe7da42457d83dbb64079b075f5628ad/Cargo.toml#L83
> 
> Was this intentional?

Nope, that one snuck past. I'm putting it back in.

**Comment by Eolu** [comment]
One comment I will make is that the EventStream API when using this with crossterm wasn't clear to me. I ended up using `attach_data_event_listener` and doing stuff like this to manually generate the appropriate crossterm events:

```rust
if event_data.starts_with('\u{1B}')
{
	let mut event_iter = event_data.split_at('\u{1B}'.len_utf8() + 2).1.split(';');
	if let (Some(Ok(mut code)), Some(Ok(x)), Some((Ok(y), m))) = 
		(event_iter.next().map(str::parse::<u8>), 
		event_iter.next().map(str::parse::<u16>), 
		event_iter.next()
			.map(|s| s.split_at(s.len() - 1))
			.map(|(y, m)| (str::parse::<u16>(y), if m == "M" {true} else {false})))
	{
		let mut modifiers = KeyModifiers::NONE;
		if code & 8 != 0
		{
			code &= !8;
			modifiers |= KeyModifiers::ALT;
		}
		if code & 16 != 0
		{
			code &= !16;
			modifiers |= KeyModifiers::CONTROL;
		}
		if code & 4 != 0
		{
			code &= !4;
			modifiers |= KeyModifiers::SHIFT;
		}
		events.push(Event::Mouse(match code
		{
			0 if m => MouseEvent {kind: MouseEventKind::Down(MouseButton::Left), column: x, row: y, modifiers},
			0 => MouseEvent {kind: MouseEventKind::Up(MouseButton::Left), column: x, row: y, modifiers},
			1 if m => MouseEvent {kind: MouseEventKind::Down(MouseButton::Middle), column: x, row: y, modifiers},
			1 => MouseEvent {kind: MouseEventKind::Up(MouseButton::Middle), column: x, row: y, modifiers},
			2 if m => MouseEvent {kind: MouseEventKind::Down(MouseButton::Right), column: x, row: y, modifiers},
			2 => MouseEvent {kind: MouseEventKind::Up(MouseButton::Right), column: x, row: y, modifiers},
			32 => MouseEvent {kind: MouseEventKind::Drag(MouseButton::Left), column: x, row: y, modifiers},
			33 => MouseEvent {kind: MouseEventKind::Drag(MouseButton::Middle), column: x, row: y, modifiers},
			34 => MouseEvent {kind: MouseEventKind::Drag(MouseButton::Right), column: x, row: y, modifiers},
			35 => MouseEvent {kind: MouseEventKind::Moved, column: x, row: y, modifiers},
			64 => MouseEvent {kind: MouseEventKind::ScrollUp, column: x, row: y, modifiers},
			65 => MouseEvent {kind: MouseEventKind::ScrollDown, column: x, row: y, modifiers},
			code => 
			{
				eprintln!("Unknown event: {}, x: {}, y: {}, m: {}", code, x, y, m);
				break;
			}
		}));
	}
}
```

I'm not sure if this level of feature is just unimplemented or I was just unclear on its implementation

**Comment by rrbutani** [comment]
Sorry, it's been a bit since I last looked at this repo.

IIRC `EventStream` should Just Work ™️ ; I've got an example usage [here](https://github.com/rrbutani/xterm-js-sys/blob/d5ba24d0157b1ce459e293b51ad5b83894d970fe/examples/with-input/src/lib.rs#L86-L116) and another one (much less readable though) in [this repo](https://github.com/ut-utp/tui) starting [here](https://github.com/ut-utp/tui/blob/592c80fe17c948b18b6725bca09fef9211757ab5/tui/src/tui/events/wasm.rs#L52-L64).

The `EventStream` API is admittedly a little tricky to use if you're not familiar with async Rust patterns; `crossterm` proper does have good docs on it and an [example usage](https://github.com/crossterm-rs/crossterm/blob/master/examples/event-stream-tokio.rs) though.

With the exception of `EventStream::new` (for dumb but necessary reasons the `xterm-js-sys` version takes a `Terminal` as an argument while the non-wasm version takes no arguments; there's some context [here](https://discord.com/channels/560857607196377088/623547693264011264/721252220074459166) and [here](https://hackmd.io/p4brrNTAR-etLzOBLTQV0A?view)) everything about the `EventStream` API for wasm should work exactly as it does on non-wasm platforms, I think.

If you've got specific questions/things that aren't making sense, feel free to ask; I'm very happy to help.

**Comment by Eolu** [comment]
Ah, well actually I figured it out - I seem to have broken the EventStream usage in this branch. I'll look into fixing it. PR not ready to merge

**Comment by Eolu** [comment]
All set, was just a few minor things with module reorganization in the latest crossterm. I'm now using EventStreams for all my events in my test app.

**Review by rrbutani — APPROVED** [review]
Sorry for the delay. This looks great; thanks!

**Pull request merged**
